import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

// Next 16 removed `next lint`; run `pnpm exec eslint .` (CI does).
const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by next-pwa at build time.
    "public/sw.js",
    "public/workbox-*.js",
    "public/fallback-*.js",
    "public/worker-*.js",
    "playwright-report/**",
    "test-results/**",
  ]),
]);

export default eslintConfig;
