"""Canonical 50-exercise catalog (data as versioned code).

The single source of truth for exercise metadata. ``scripts/seed_exercises.py``
writes these rows into the DB; templates and tests import the ids from here so a
template can never reference a non-existent exercise.

``youtube_video_id`` is intentionally None — see scripts/EXERCISE_VIDEOS.md.
"""

from __future__ import annotations

from typing import Any

BW = ["bodyweight"]
GYM = ["college_gym"]


def _ex(id: str, name: str, primary: str, secondary: list[str], equipment: list[str], sets: int, reps: str, rest: int, instr: str, mistakes: list[str]) -> dict[str, Any]:
    return {
        "id": id,
        "name": name,
        "primary_muscle": primary,
        "secondary_muscles": secondary,
        "equipment": equipment,
        "default_sets": sets,
        "default_reps": reps,
        "rest_seconds": rest,
        "youtube_video_id": None,  # curate later (see README)
        "instruction_text": instr,
        "common_mistakes": mistakes,
    }


EXERCISES = [
    # ── Bodyweight upper (7) ──────────────────────────────────────────────
    _ex("pushup", "Push-up", "chest", ["triceps", "front_delts", "core"], BW, 3, "8-12", 60,
        "Hands shoulder-width, body in a straight line from head to heels. Lower until your chest is just above the floor, then push back up.",
        ["Sagging hips — brace your core", "Elbows flaring to 90° — keep them ~45° tucked", "Half reps — lower your chest to the floor"]),
    _ex("incline_pushup", "Incline Push-up", "chest", ["triceps", "front_delts"], BW, 3, "10-15", 60,
        "Hands on a desk or bed edge, body straight. Lower chest to the surface and press up. Easier than a floor push-up — good for building up.",
        ["Hips piking up", "Hands too far forward", "Rushing the lowering phase"]),
    _ex("decline_pushup", "Decline Push-up", "chest", ["front_delts", "triceps", "core"], BW, 3, "8-12", 75,
        "Feet elevated on a bed or chair, hands on the floor. Lower under control and press up. Shifts emphasis to the upper chest and shoulders.",
        ["Letting hips sag", "Head dropping toward the floor", "Feet too high, losing the straight line"]),
    _ex("diamond_pushup", "Diamond Push-up", "triceps", ["chest", "front_delts"], BW, 3, "6-10", 75,
        "Hands together under the chest forming a diamond. Lower until the chest touches your hands, keeping elbows close to the body.",
        ["Elbows flaring out", "Not going full range", "Wrists strained — slightly stagger if needed"]),
    _ex("pike_pushup", "Pike Push-up", "shoulders", ["triceps", "upper_chest"], BW, 3, "6-10", 75,
        "Hips high in an inverted-V, head pointing down. Bend the elbows to lower the crown of your head toward the floor, then press up. A shoulder builder.",
        ["Bending at the hips instead of the elbows", "Hands too far from feet", "Not lowering far enough"]),
    _ex("chair_dip", "Chair Dip", "triceps", ["chest", "front_delts"], BW, 3, "8-12", 60,
        "Hands on a sturdy chair edge behind you, legs out front. Bend the elbows to lower your hips, then press back up.",
        ["Shoulders shrugging up to the ears", "Going too deep and straining the shoulders", "Using legs to push instead of triceps"]),
    _ex("plank_shoulder_tap", "Plank Shoulder Tap", "core", ["shoulders", "chest"], BW, 3, "20-30 taps", 45,
        "From a high plank, tap each hand to the opposite shoulder while keeping hips as still as possible.",
        ["Hips rocking side to side", "Feet too close together", "Holding your breath"]),

    # ── Bodyweight lower (10) ─────────────────────────────────────────────
    _ex("squat", "Bodyweight Squat", "quads", ["glutes", "hamstrings", "core"], BW, 3, "12-20", 60,
        "Feet shoulder-width, toes slightly out. Sit back and down until thighs are at least parallel, chest up, then drive through the heels.",
        ["Knees caving inward", "Heels lifting off the floor", "Not reaching depth"]),
    _ex("jump_squat", "Jump Squat", "quads", ["glutes", "calves", "core"], BW, 3, "8-12", 75,
        "Squat down, then explode up into a jump. Land softly with bent knees and immediately sink into the next rep.",
        ["Landing with stiff legs", "Shallow squat before the jump", "Knees caving on landing"]),
    _ex("pistol_squat_assisted", "Assisted Pistol Squat", "quads", ["glutes", "hamstrings", "core"], BW, 3, "5-8 each", 75,
        "Hold a doorframe or chair for balance. Lower on one leg with the other extended forward, then stand back up.",
        ["Collapsing at the bottom", "Heel lifting", "Pulling too hard with the arm instead of using the leg"]),
    _ex("forward_lunge", "Forward Lunge", "quads", ["glutes", "hamstrings"], BW, 3, "10-12 each", 60,
        "Step forward and lower until both knees are ~90°, front knee over the ankle. Push back to standing.",
        ["Front knee travelling past the toes", "Leaning the torso forward", "Short step shortening the range"]),
    _ex("reverse_lunge", "Reverse Lunge", "glutes", ["quads", "hamstrings"], BW, 3, "10-12 each", 60,
        "Step backward and lower until both knees are ~90°. Drive through the front heel to return. Easier on the knees than the forward lunge.",
        ["Torso tipping forward", "Front heel lifting", "Stepping too short"]),
    _ex("bulgarian_split_squat", "Bulgarian Split Squat (Chair)", "quads", ["glutes", "hamstrings", "core"], BW, 3, "8-12 each", 75,
        "Rear foot resting on a chair, front foot forward. Lower straight down until the front thigh is parallel, then drive up.",
        ["Front foot too close to the chair", "Knee caving in", "Bouncing out of the bottom"]),
    _ex("glute_bridge", "Glute Bridge", "glutes", ["hamstrings", "core"], BW, 3, "15-20", 45,
        "Lie on your back, knees bent, feet flat. Drive through the heels to lift the hips until the body is straight from knees to shoulders; squeeze the glutes.",
        ["Overarching the lower back instead of squeezing glutes", "Pushing through the toes", "Not pausing at the top"]),
    _ex("single_leg_glute_bridge", "Single-Leg Glute Bridge", "glutes", ["hamstrings", "core"], BW, 3, "10-12 each", 60,
        "Glute bridge with one leg extended. Lift the hips using the planted leg, keeping the pelvis level.",
        ["Hips dropping on the free-leg side", "Arching the lower back", "Pushing through the toes"]),
    _ex("wall_sit", "Wall Sit", "quads", ["glutes", "calves"], BW, 3, "30-60s", 60,
        "Back flat against a wall, slide down until thighs are parallel to the floor, knees over ankles. Hold.",
        ["Knees past the toes", "Hips creeping up over time", "Putting hands on the thighs for support"]),
    _ex("calf_raise", "Standing Calf Raise", "calves", [], BW, 3, "15-20", 45,
        "Stand tall, rise onto the balls of the feet as high as possible, pause, then lower under control. Use a step for more range.",
        ["Bouncing through reps", "Not reaching full height", "Rolling onto the outer edges of the feet"]),

    # ── Bodyweight core (9) ───────────────────────────────────────────────
    _ex("plank", "Plank", "core", ["shoulders", "glutes"], BW, 3, "30-60s", 45,
        "Forearms under the shoulders, body in a straight line. Brace the abs and squeeze the glutes; breathe steadily.",
        ["Hips sagging", "Hips piking up", "Holding your breath"]),
    _ex("side_plank", "Side Plank", "obliques", ["core", "shoulders"], BW, 3, "20-40s each", 45,
        "On one forearm, body in a straight line, hips stacked. Lift the hips and hold without letting them drop.",
        ["Hips dropping toward the floor", "Rotating the torso forward", "Supporting shoulder collapsing"]),
    _ex("hollow_hold", "Hollow Hold", "core", ["hip_flexors"], BW, 3, "20-40s", 45,
        "On your back, press the lower back into the floor, lift the shoulders and legs into a shallow banana shape. Hold.",
        ["Lower back arching off the floor", "Legs too low straining the back", "Holding your breath"]),
    _ex("crunch", "Crunch", "core", [], BW, 3, "15-20", 40,
        "Knees bent, hands by the head. Curl the shoulder blades off the floor by contracting the abs, then lower under control.",
        ["Pulling on the neck", "Using momentum to swing up", "Lifting the whole back instead of curling"]),
    _ex("leg_raise", "Lying Leg Raise", "lower_abs", ["hip_flexors"], BW, 3, "10-15", 45,
        "On your back, legs straight. Keeping the lower back flat, raise the legs to vertical, then lower slowly without touching the floor.",
        ["Lower back arching as legs lower", "Bending the knees too much", "Dropping the legs quickly"]),
    _ex("bicycle_crunch", "Bicycle Crunch", "obliques", ["core", "hip_flexors"], BW, 3, "20-30 total", 40,
        "Alternate bringing each elbow toward the opposite knee while extending the other leg, in a smooth pedalling motion.",
        ["Yanking the neck", "Going too fast and losing control", "Not extending the legs fully"]),
    _ex("mountain_climber", "Mountain Climber", "core", ["shoulders", "quads", "cardio"], BW, 3, "30-40s", 40,
        "From a high plank, drive the knees toward the chest one at a time, quickly, keeping the hips low.",
        ["Hips bouncing high", "Hands drifting forward", "Feet not coming through fully"]),
    _ex("dead_bug", "Dead Bug", "core", ["hip_flexors"], BW, 3, "8-12 each", 45,
        "On your back, arms up and knees over hips. Slowly lower the opposite arm and leg, keeping the lower back pressed down, then switch.",
        ["Lower back arching off the floor", "Moving too fast", "Holding the breath instead of exhaling on the reach"]),
    _ex("bird_dog", "Bird Dog", "core", ["glutes", "lower_back"], BW, 3, "10-12 each", 45,
        "On all fours, extend the opposite arm and leg until level with the torso, pause, then return. Keep the hips square.",
        ["Hips rotating open", "Overarching the lower back", "Rushing instead of controlling the reach"]),

    # ── Bodyweight back / pull (3) ────────────────────────────────────────
    _ex("doorway_row", "Doorway Towel Row", "back", ["biceps", "rear_delts"], BW, 3, "10-15", 60,
        "Loop a towel around a sturdy doorknob (both sides), lean back with straight arms, then pull the chest toward the door, squeezing the shoulder blades.",
        ["Pulling with the arms only", "Not leaning back far enough for resistance", "Rounding the upper back"]),
    _ex("inverted_row_table", "Inverted Row (Table)", "back", ["biceps", "rear_delts", "core"], BW, 3, "8-12", 75,
        "Lie under a sturdy table, grip the edge, body straight. Pull your chest up to the table edge, then lower under control.",
        ["Hips sagging", "Partial range — pull all the way up", "Shrugging the shoulders"]),
    _ex("superman", "Superman", "lower_back", ["glutes", "rear_delts"], BW, 3, "12-15", 45,
        "Lie face down, arms extended forward. Lift the arms, chest, and legs off the floor, squeeze, then lower.",
        ["Jerking up with momentum", "Looking up and straining the neck", "Not pausing at the top"]),

    # ── Cardio circuits (5) ───────────────────────────────────────────────
    _ex("burpee", "Burpee", "full_body", ["chest", "quads", "cardio"], BW, 3, "10-15", 60,
        "From standing, drop to a squat, kick back to a plank, do a push-up, jump the feet in, then jump up. A full-body conditioning move.",
        ["Skipping the push-up or the jump", "Sagging hips in the plank", "Landing hard on straight legs"]),
    _ex("high_knees", "High Knees", "cardio", ["quads", "core", "calves"], BW, 3, "30-40s", 30,
        "Run in place driving the knees up to hip height, landing softly on the balls of the feet, arms pumping.",
        ["Knees not reaching hip height", "Landing flat-footed", "Leaning too far back"]),
    _ex("jumping_jack", "Jumping Jacks", "cardio", ["shoulders", "calves"], BW, 3, "30-45s", 30,
        "Jump the feet out while raising the arms overhead, then jump back in. Keep a steady rhythm.",
        ["Half-raising the arms", "Stiff, heavy landings", "Losing rhythm and rushing"]),
    _ex("skater", "Skater Hops", "glutes", ["quads", "cardio", "calves"], BW, 3, "30-40s", 40,
        "Leap laterally from one foot to the other, landing softly with a slight knee bend and the trailing leg behind, like a speed skater.",
        ["Landing stiff-legged", "Not pushing off laterally enough", "Knee caving on landing"]),
    _ex("jump_rope", "Jump Rope", "cardio", ["calves", "shoulders"], BW, 3, "45-60s", 40,
        "Turn the rope with the wrists and hop just high enough to clear it, landing softly on the balls of the feet. (No rope? Simulate the motion.)",
        ["Jumping too high and tiring fast", "Turning from the shoulders not the wrists", "Landing flat-footed"]),

    # ── Gym compound (10) ─────────────────────────────────────────────────
    _ex("bench_press", "Barbell Bench Press", "chest", ["triceps", "front_delts"], GYM, 4, "6-10", 120,
        "Lie flat, grip slightly wider than shoulders. Lower the bar to mid-chest with elbows ~45°, then press up to lockout. Use a spotter.",
        ["Bouncing the bar off the chest", "Flaring elbows to 90°", "Lifting the hips off the bench"]),
    _ex("incline_bench_press", "Incline Bench Press", "upper_chest", ["front_delts", "triceps"], GYM, 3, "8-12", 120,
        "Bench set to ~30°. Lower the bar to the upper chest, then press up. Emphasises the upper chest.",
        ["Setting the incline too steep (turns into a shoulder press)", "Bouncing the bar", "Partial range"]),
    _ex("overhead_press", "Overhead Press", "shoulders", ["triceps", "upper_chest", "core"], GYM, 4, "6-10", 120,
        "Standing, bar at the collarbone. Brace the core and press overhead to lockout, moving the head slightly back then through.",
        ["Overarching the lower back", "Pressing the bar forward instead of up", "Not locking out overhead"]),
    _ex("deadlift", "Deadlift", "back", ["glutes", "hamstrings", "core"], GYM, 4, "5-8", 150,
        "Bar over mid-foot, hinge and grip just outside the knees, flat back. Drive through the floor, keeping the bar close, to stand tall.",
        ["Rounding the lower back", "Bar drifting away from the shins", "Hips shooting up before the bar moves"]),
    _ex("barbell_row", "Barbell Row", "back", ["biceps", "rear_delts"], GYM, 3, "8-12", 90,
        "Hinge to ~45°, flat back. Pull the bar to the lower ribs, squeezing the shoulder blades, then lower under control.",
        ["Standing too upright", "Using momentum / heaving", "Rounding the back"]),
    _ex("pullup", "Pull-up", "back", ["biceps", "rear_delts", "core"], GYM, 3, "5-10", 120,
        "Hang from the bar, hands just wider than shoulders. Pull the chest toward the bar by driving the elbows down, then lower fully.",
        ["Partial range (chin not over the bar)", "Kipping / swinging", "Not controlling the descent"]),
    _ex("lat_pulldown", "Lat Pulldown", "back", ["biceps", "rear_delts"], GYM, 3, "10-12", 75,
        "Grip wider than shoulders, slight lean back. Pull the bar to the upper chest, driving the elbows down and squeezing the lats.",
        ["Pulling behind the neck", "Using body sway for momentum", "Bar not reaching the chest"]),
    _ex("barbell_squat", "Barbell Back Squat", "quads", ["glutes", "hamstrings", "core"], GYM, 4, "6-10", 150,
        "Bar on the upper back, feet shoulder-width. Sit back and down to at least parallel, chest up, then drive through the heels.",
        ["Knees caving in", "Heels lifting / shifting onto the toes", "Rounding the back at the bottom"]),
    _ex("leg_press", "Leg Press", "quads", ["glutes", "hamstrings"], GYM, 3, "10-15", 90,
        "Feet shoulder-width on the platform. Lower until the knees reach ~90°, then press without locking out hard at the top.",
        ["Letting the lower back round off the pad", "Locking the knees aggressively", "Half reps"]),
    _ex("romanian_deadlift", "Romanian Deadlift", "hamstrings", ["glutes", "lower_back"], GYM, 3, "8-12", 120,
        "Soft knees, hinge at the hips pushing them back, lowering the bar along the thighs until you feel a hamstring stretch, then stand.",
        ["Rounding the back", "Bending the knees too much (turns into a squat)", "Bar drifting away from the legs"]),

    # ── Gym isolation (6) ─────────────────────────────────────────────────
    _ex("bicep_curl", "Dumbbell Bicep Curl", "biceps", ["forearms"], GYM, 3, "10-15", 60,
        "Elbows pinned to the sides, curl the weights up by flexing the biceps, then lower under control.",
        ["Swinging the body for momentum", "Elbows drifting forward", "Not fully extending at the bottom"]),
    _ex("tricep_pushdown", "Tricep Pushdown", "triceps", [], GYM, 3, "10-15", 60,
        "At a cable, elbows pinned to the sides. Extend the arms down to lockout, then return under control.",
        ["Elbows flaring out and away", "Leaning over to push with body weight", "Partial lockout"]),
    _ex("lateral_raise", "Lateral Raise", "side_delts", [], GYM, 3, "12-15", 60,
        "Slight bend in the elbows, raise the weights out to the sides to shoulder height, leading with the elbows, then lower slowly.",
        ["Using momentum to swing up", "Raising above shoulder height / shrugging", "Going too heavy and losing form"]),
    _ex("leg_extension", "Leg Extension", "quads", [], GYM, 3, "12-15", 60,
        "Seated, extend the knees to straighten the legs against the pad, squeeze the quads at the top, then lower under control.",
        ["Using momentum / kicking", "Not pausing at the top", "Setting the pad too high on the shin"]),
    _ex("leg_curl", "Leg Curl", "hamstrings", ["calves"], GYM, 3, "12-15", 60,
        "Curl the pad toward the glutes by flexing the hamstrings, squeeze, then lower slowly.",
        ["Lifting the hips off the pad", "Using momentum", "Partial range of motion"]),
    _ex("calf_raise_machine", "Calf Raise (Machine)", "calves", [], GYM, 3, "15-20", 45,
        "Balls of the feet on the platform. Rise as high as possible, pause, then lower into a deep stretch under control.",
        ["Bouncing through reps", "Short range of motion", "Bending the knees to cheat the weight up"]),
]
